version: '3.3'
services:

  jobmanager:
    image: flink:1.12.2-scala_2.12
    volumes:
      - ./logs/jobmanager/:/opt/flink/log/
      - ./config/flink-jars/:/opt/flink/connector-lib/
      - ./logs/flink-checkpoints/:/flink-checkpoints
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: rocksdb
        state.checkpoints.dir: file:///flink-checkpoints

  taskmanager:
    image: flink:1.12.2-scala_2.12
    volumes:
      - ./logs/taskmanager/:/opt/flink/log/
      - ./logs/flink-checkpoints/:/flink-checkpoints
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        state.backend: rocksdb
        state.checkpoints.dir: file:///flink-checkpoints

  # zookeeper:
  #   image: wurstmeister/zookeeper:3.4.6
  #   ports:
  #     - "2181:2181"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    security_opt:
      - seccomp:unconfined

  pd:
    image: pingcap/pd:latest
    ports:
      - "2379"
    volumes:
      - ./config/tidb-config/pd.toml:/pd.toml:ro
      - ./logs/tidbs:/logs/
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --data-dir=/data/pd
      - --config=/pd.toml
      - --log-file=/logs/pd.log
    restart: on-failure

  tikv:
    image: pingcap/tikv:latest
    volumes:
      - ./config/tidb-config/tikv.toml:/tikv.toml:ro
      - ./logs/tidbs:/logs/
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/data/tikv
      - --pd=pd:2379
      - --config=/tikv.toml
      - --log-file=/logs/tikv.log
    depends_on:
      - "pd"
    restart: on-failure

  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb-config/tidb.toml:/tidb.toml:ro
      - ./logs/tidbs:/logs/
    command:
      - --store=tikv
      - --path=pd:2379
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --log-slow-query=/logs/tidb_slow.log
      - --advertise-address=tidb
    depends_on:
      - "tikv"
    restart: on-failure